name = "universo-sustentavel"
compatibility_date = "2024-01-01"

[site]
bucket = "build/client"

[pages]
project_name = "universo-sustentavel"
pages_build_output_dir = "build/client"

[build]
command = "pnpm run build"
output_dir = "build/client"
